

<div id="footer">
<h2>Petrol Refinería | Álvaro Obregón 49, 2o. piso, Col. Roma. México, D.F. | T. 55 5207 3624</h2>
<h2><a href="https://twitter.com/PetrolRefineria" target="_blank">Twitter</a> | <a href="https://www.facebook.com/PetrolRefineria" target="_blank">Facebook</a> | <a href="http://instagram.com/petrolrefineria" target="_blank">Instagram</a> | <a href="http://www.pinterest.com/PetrolRefineria" target="_blank">Pinterest</a> | <a href="https://maps.google.com/maps?q=Avenida+%C3%81lvaro+Obreg%C3%B3n+49,+Colonia+Roma,+Cuauht%C3%A9moc,+Mexico+City,+Mexico&hl=en&ie=UTF8&sll=37.0625,-95.677068&sspn=64.241198,124.013672&oq=%C3%81lvaro+Obreg%C3%B3n+49+col+roma+me&hnear=Av+%C3%81lvaro+Obreg%C3%B3n+49,+Roma+Norte,+Cuauht%C3%A9moc,+Ciudad+de+M%C3%A9xico,+Distrito+Federal,+Mexico&t=m&z=17" target="_blank">Google Maps</a></h2>
</div>

<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-53507608-1', 'auto');
  ga('send', 'pageview');

</script>