
<div id="menu">
	
	<img src="images/petrol_logo_main.png" alt="Petrol Refinería" id="logoPetrol" />
	
	<ul id="nav">
		<li><a href="#ropa" target="_self" rel="ropa.php">ropa</a></li>
		<li><a href="#calzado" target="_self" rel="calzado.php">calzado</a></li>
		<li><a href="#bolsas" target="_self" rel="bolsas.php">bolsas</a></li>
		<li><a href="#joyeria" target="_self" rel="joyeria.php">joyería</a></li>
		<li><a href="#lentes" target="_self" rel="lentes.php">lentes</a></li>
		<li><a href="#muebles" target="_self" rel="muebles.php">muebles</a></li>
		<div class="clearfix"></div>
	</ul>
	
</div>
