	<link rel="shortcut icon" type="image/x-icon" href="favicon.ico" />
		
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	
	<meta name="author" content="Sandra Bermudez @ bulabe.com" />
	<meta name="description" content=""/>
	<meta name="keywords" content=""/>
	
	<meta property="og:title" content="Petrol" />
	<meta property="og:type" content="website" />
	<meta property="og:description" content="Refinería Petrol" />
	<meta property="og:url" content="http://" />
	<meta property="og:image" content="http://" />
	
	<link rel="stylesheet" type="text/css" href="style.css" />
	
	<script type="text/javascript" src="js/jquery-1.11.0.min.js"></script>
	<script type="text/javascript" src="js/jquery.easing.1.3.js"></script>
	<script type="text/javascript" src="js/jquery.color-2.1.2.min.js"></script>
	<script type="text/javascript" src="js/jquery.frontend.js"></script>